algo = input('Digite algo: ')
print(f'O tipo primitivo desse valor é: {type(algo)}')
print(f'Só tem espaço? {algo.isspace()}')
print(f'É um número: {algo.isnumeric()}')
print(f'É alfabético: {algo.isalpha()}')
print(f'É alfanúmerico: {algo.isalnum()}')
print(f'Está em maiusculas? {algo.isupper()}')
print(f'Está em minusculo? {algo.islower()}')
print(f'Está capitalizada? {algo.istitle()}')
